server:
  port: 8889 #网关的端口
management:
  endpoints:
    web:
      exposure:
        include: '*' #暴露端点，这样actuator就可以监控的到健康状况
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
#  config: classpath:logback-spring.xml

#http://localhost:9921/product/ahas
#现在我们在浏览器访问: http://localhost:9921/actuator/gateway/routes


nacos:
  config:
    server-addr: 127.0.0.1:8848 #nacos的serverAdd配置
    group: NAOCS-SPRING-CLOUD-GATEWAY #分组的配置
    file-extension: json
    data-id: spring-cloud-gateway.json #data-id的配置
